// Quick script to add some sample entries for testing
// Run this while server is NOT running, or use the admin interface

const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.join(__dirname, 'data', 'dsdorg.db');
const db = new sqlite3.Database(dbPath);

function createSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

const sampleEntries = [
  {
    title: 'first entry - testing the waters',
    category: 'text',
    content_type: 'markdown',
    content: `# welcome to dsd.org

this is my first entry. just testing things out.

i wanted a place where i could document **everything** - thoughts, photos, code snippets, whatever.

this site is intentionally rough around the edges. i like it that way.

## what is this?

a life portfolio. a digital journal. a time capsule.

### some things to know:

- no fancy frameworks
- just raw html, css, and javascript
- early internet vibes
- moody purple-pink color scheme

i'll be adding more entries as time goes on. this is just the beginning.

---

*jan 19, 2026*`
  },
  {
    title: 'on nostalgia and web design',
    category: 'text',
    content_type: 'markdown',
    content: `there's something special about the early internet aesthetic. 

before everything became polished and corporate. before every website looked the same.

> "the web used to be more human"

i want this space to feel **handmade**. like someone actually built it, not like it was generated by some template.

things i miss about old websites:
- visible borders everywhere
- guestbooks
- hit counters (maybe i'll add one just for fun)
- under construction gifs (okay maybe not those)
- personal expression over professionalism

this site is my rebellion against modern web design trends.`
  },
  {
    title: 'color palette notes',
    category: 'code',
    content_type: 'markdown',
    content: `# color scheme documentation

decided on a moody romantic palette. here's what i'm using:

\`\`\`
primary background: #1a1625 (deep purple-black)
secondary background: #2d1b3d (muted plum)
text primary: #e8d5d0 (warm cream)
text secondary: #b89eb5 (dusty rose-gray)
accent 1: #8b5a7c (mauve)
accent 2: #d4738f (rose)
link color: #c97a9e (soft pink)
borders: #4a3550 (dark purple-gray)
\`\`\`

the whole vibe is meant to feel like candlelight. dim, intimate, personal.

i spent way too long tweaking these but i think it's worth it.`
  }
];

console.log('Adding sample entries...');

let added = 0;
sampleEntries.forEach((entry, index) => {
  const slug = createSlug(entry.title);
  const sql = `
    INSERT INTO entries (title, slug, category, content_type, content)
    VALUES (?, ?, ?, ?, ?)
  `;
  
  db.run(sql, [entry.title, slug, entry.category, entry.content_type, entry.content], function(err) {
    if (err) {
      console.error(`Error adding entry ${index + 1}:`, err.message);
    } else {
      console.log(`Added entry ${index + 1}: "${entry.title}" (ID: ${this.lastID})`);
      added++;
      
      if (added === sampleEntries.length) {
        console.log('\nAll sample entries added!');
        console.log('Visit http://localhost:3000 to see them');
        db.close();
        process.exit(0);
      }
    }
  });
});

setTimeout(() => {
  if (added < sampleEntries.length) {
    console.error('\nTimeout - some entries may not have been added');
    db.close();
    process.exit(1);
  }
}, 5000);

